### ISSUE TITLE
[2020.05.09] Front-end TODO list

### ISSUE THREAD

**Issue by MSWon** [kanban-project/Front-end#1]
## Front-end
- ```민섭```
   - [x] javascript 기초 공부
   - [x] React 기초 공부
   - [x] 칸반보드 css, html 양식 인터넷에 찾아보기
   - [x] Backend한테 요청할 REST API 양식 고민 및 받은 데이터로 웹페이지 구성
   - [ ] 드래그앤 드롭 기능 구현

- ```근영```
   - [x] javascript 기초 공부
   - [x] React 기초 공부
   - [ ] 칸반보드 css, html 양식 인터넷에 찾아보기
   - [ ] Backend한테 요청할 REST API 양식 고민 및 받은 데이터로 웹페이지 구성
   - [ ] 드래그앤 드롭 기능 구현
